services:
  node:
    build:
      context: ./
      dockerfile: docker/node/Dockerfile.dev
    container_name: node
    volumes:
      - ./api:/home/node/app/api
    ports:
      - "3006:3006"
    depends_on:
      mysql-db:
        condition: service_healthy
    env_file:
      - .env

  mysql-db:
    build:
      context: ./
      dockerfile: docker/mysql/Dockerfile.dev
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql-db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql-db

volumes:
  mysql_data: